version: "3.6"
services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
    - 80:80
  backend:
    build: backend
    volumes:
      - ./backend:/go/src/online_crosswords
